# Generated by Django 2.2.3 on 2019-10-22 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('mobile', models.IntegerField(blank=True, null=True, unique=True)),
                ('emergency_mobile', models.IntegerField(blank=True, null=True)),
                ('photo', models.URLField(default='any')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('height', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_gym_owner', models.BooleanField(default=False)),
                ('is_gym_employee', models.BooleanField(default=False)),
                ('is_gym_client', models.BooleanField(default=False)),
                ('email_verifed', models.BooleanField(default=False)),
                ('mobile_verifed', models.BooleanField(default=False)),
                ('activation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modfied', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
