# Generated by Django 2.2.3 on 2019-10-29 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_auto_20191029_1248'),
        ('branches', '0001_initial'),
        ('employees', '0008_auto_20191029_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('date_locked', models.DateTimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('vip_capacity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CoachClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('vip_capacity', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
                ('coach', models.ForeignKey(on_delete=None, to='employees.Employee')),
                ('days', models.ManyToManyField(to='classes.Days')),
            ],
        ),
        migrations.CreateModel(
            name='ClientsAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_present', models.BooleanField(default=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_modified', models.DateField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=None, to='employees.Employee')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassSession')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='coach_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.CoachClasses'),
        ),
    ]
