# Generated by Django 2.2.3 on 2019-10-22 18:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('civil_id', models.CharField(max_length=255, unique=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('F', 'Famale'), ('M', 'Male')], max_length=1, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('referred_by', models.CharField(blank=True, max_length=50, null=True)),
                ('relatives', models.CharField(blank=True, max_length=50, null=True)),
                ('create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_modified', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch')),
            ],
        ),
    ]
