# Generated by Django 2.2.3 on 2019-10-25 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must not contain special characters', regex='^[-\\w\\s]*$'), django.core.validators.RegexValidator(code='invalid_name', message='Name must be alphabetic', regex='^[^0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Famale')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must not contain special characters', regex='^[-\\w\\s]*$'), django.core.validators.RegexValidator(code='invalid_name', message='Name must be alphabetic', regex='^[^0-9_]*$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must not contain special characters', regex='^[-\\w\\s]*$'), django.core.validators.RegexValidator(code='invalid_name', message='Name must be alphabetic', regex='^[^0-9_]*$')]),
        ),
    ]
