# Generated by Django 2.2.3 on 2019-10-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('clients', '0002_auto_20191026_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gyms.Gym'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('F', 'Famale'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
    ]
