# Generated by Django 2.2.3 on 2019-10-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20191028_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Famale')], max_length=1, verbose_name='Gender'),
        ),
    ]
