# Generated by Django 2.2.3 on 2019-10-22 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('price_name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('sessions', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('extra_days', models.PositiveIntegerField()),
                ('extra_sessions', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('sessions_valid_to', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('package', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('gym', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_modified', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
        ),
    ]
