# Generated by Django 2.2.3 on 2019-10-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='gym',
        ),
        migrations.AlterField(
            model_name='membership',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.Branch'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Package'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Price'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Service'),
        ),
    ]
