# Generated by Django 2.2.3 on 2019-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20191024_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Service_name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='membership',
            name='service_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
