# Generated by Django 2.2.3 on 2019-10-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20191024_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.FloatField(default=0)),
                ('debit_amount', models.FloatField(default=0)),
                ('debit_refrence', models.IntegerField(default=0)),
                ('credit_amount', models.FloatField(default=0)),
                ('credit_refrence', models.IntegerField(default=0)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.Membership')),
            ],
        ),
    ]
