# Generated by Django 2.2.3 on 2019-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_membershippayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='original_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
