# Generated by Django 2.2.3 on 2019-10-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20191026_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
