# Generated by Django 2.2.3 on 2019-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20191029_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sessions_valid_to',
            field=models.DateField(verbose_name='sessions_valid'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(verbose_name='start'),
        ),
    ]
