# Generated by Django 2.2.3 on 2019-10-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gym_name', models.CharField(max_length=255)),
                ('logo', models.URLField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('currency_symbol', models.CharField(max_length=5)),
                ('tax', models.FloatField(default=0)),
                ('phone', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modfied', models.DateTimeField(default=django.utils.timezone.now)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
