# Generated by Django 2.2.3 on 2019-10-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='admins',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
