# Generated by Django 2.2.3 on 2019-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_auto_20191029_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='admins',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
