# Generated by Django 2.2.3 on 2019-12-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('being', 'being'), ('pickup', 'pickup')], max_length=6, verbose_name='Gender')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
