# Generated by Django 2.2.3 on 2019-12-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='gender',
            new_name='status',
        ),
    ]
