# Generated by Django 2.2.3 on 2019-12-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0002_auto_20191207_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('being', 'being'), ('new', 'new'), ('pickup', 'pickup')], max_length=6, verbose_name='status'),
        ),
    ]
