# Generated by Django 2.2.3 on 2019-12-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0003_auto_20191207_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pickup', 'pickup'), ('new', 'new'), ('being', 'being')], max_length=6, verbose_name='status'),
        ),
    ]
