# Generated by Django 2.2.3 on 2019-12-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0005_auto_20191207_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pickup', 'pickup'), ('being', 'being'), ('ready', 'ready')], max_length=6, verbose_name='status'),
        ),
    ]
